[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fringe"
version = "5.2.dev0"
requires-python = ">= 3.13"
license = {file = "LICENSE"}
readme = "README.md"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "pillow>=11.1.0",
]

[project.scripts]
fringe-app = "fringe:app.show_gui"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
]

[tool.pytest.ini_options]
cache_dir = ".cache/pytest"
addopts = [
  "--cov=src",
  "--cov-report=html",
  "--verbose",
  "--import-mode=importlib",
]

[tool.coverage.run]
branch = true
data_file = ".cache/coverage/.coverage"

[tool.coverage.report]
omit = [
  "app.py",
  "poly_lasso.py",
]

[tool.coverage.html]
directory = ".cache/coverage"
title = "FringeApp coverage report"
